spring:
  application:
    name: cofrinhos-api

  datasource:
    url: jdbc:postgresql://localhost:5432/cofrinhos
    username: cofrinhos
    password: cofrinhos

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: cofrinhos-api
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.enzoanthonydev.cofrinhos.cofrinhos_api.application.aporte
    template:
      observation-enabled: true
    listener:
      observation-enabled: true

  data:
    redis:
      host: localhost
      port: 6379
      repositories:
        enabled: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/cofrinhos

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
  otlp:
    metrics:
      export:
        enabled: false
  tracing:
    sampling:
      probability: 1.0
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces

server:
  port: 8080